---
title: '기공수 과제 #1'
author: "20192208 김형훈"
format: 
  pdf:
    documentclass: report
    papersize: a4
    number-sections: true
    number-depth: 3
    top-level-division: chapter
    geometry:
      - top=10mm
include-in-header: 
  text: |
    \usepackage{fontspec} 
    \setmainfont{NanumGothic}
    \usepackage{titlesec}
    \titleformat{\chapter}{\normalfont\huge\bfseries}{\thechapter.}{20pt}{\huge}
    \titleformat{\section}[block]{\normalfont\Large\bfseries}{}{0pt}{}
    \titleformat{\subsection}[block]{\normalfont\large\bfseries}{}{0pt}{}
    \titleformat{\subsubsection}[block]{\normalfont\normalsize\bfseries}{}{0pt}{}
    \titlespacing*{\chapter}{0pt}{-20pt}{10pt}
    \usepackage{setspace}
    \setstretch{1.5}
---

# 1장 1절
## 2번 문제
### 공집합인 집합을 구하여라.
#### 1. A = {x | x² + 1 = 0, x는 복소수}

$x^2 + 1 = 0$  
$x^2 = -1$  
$x = \pm{\sqrt{-1}}$  
$x = \pm{i}$  
$A = \{+i, -i\}$ 이므로 공집합이 아니다.

#### 2. B = {y | y² + 1 = 0, y는 실수}

$y² + 1 = 0$  
$y² = -1$  
$y = \pm{\sqrt{-1}}$  
$y = \pm{i}$  
$B = \{+i, -i\}$ 이므로 공집합이 아니다.  
...라고 생각할 수 있으나 y의 범위는 실수이므로 허수는 포함할 수 없기때문에 공집합이다.

#### 3. C = {z | z + 1 = 0, z + 2 = 0, z는 복소수}

$z = -1$, $z = -2$  
$C = \{-1 + 0 * i, -2 + 0 * i\}$ 이므로 공집합이 아니다.

#### 4. D = {t | sin t = 2, t는 실수}

$sin t = 2$  
$-1 ≤ sin t ≤ 1$  
$sin t$는 2가 될 수 없으므로 공집합.  


**답은 2번과 4번.  **

# 1장 2절
## 2번 문제
### 다음 실수의 부분집합 A, B, C가 유계임을 보이고, 상계와 하계를 하나씩 구하여라.

#### 1. $A = \{x \vert x = \frac{1}{2n}, n \in N\}$
$n$이 커질수록 $x$는 0에 가까워진다.  
따라서 **하계는 0**, **상계는 $n$이 1일때의 값인 $\frac{1}{2}$**이다.

#### 2. $B = \{y \vert y = \frac{n + 1}{n}, n \in N\}$
$n$이 커질수록 $y$는 상대 비율인 1에 가까워진다.  
따라서 **하계는 1**, **상계는 $n$이 1일때의 값인 2**이다.

#### 3. $C = \{z \vert z = 1 - \frac{1}{n}, n \in N\}$
$n$이 커질수록 $z$는 1에 가까워진다.  
따라서 **상계는 1**, **하계는 $n$이 1일때의 값인 0**이다.

# 1장 3절
## 2번 문제
### 다음 함수의 정의역과 치역을 구하여라.

#### 1. $y = \frac{1}{x² + 1}$
- 정의역:  
  분모가 0인경우 식이 성립할 수 없다.  
  이 경우 분모가 0이 되는 $x$는 $x^2 = -1$인 $x$이다.  
  $x^2 = -1$인 $x$는 실수에서는 존재하지 않으므로 정의역은 모든 실수이다.  
- 치역:  
  $x^2 + 1 >= 1$, 이의 역수로 식을 다시 구하면, $\frac{1}{(x² + 1)} <= 1$  
  $x$가 무한히 커지거나 작아질수록 $y$는 0에 가까워진다.  
  따라서 치역은 (0, 1]이다.

#### 2. $y = sin (\frac{1}{x})$
- 정의역: 0을 제외한 모든 실수
- 치역: [-1, 1]

#### 3. $y = tanx$
- 정의역: $tanx = \frac{sinx}{cosx}$, 즉 $cosx \neq 0$.  
  $cosx = 0$인 경우는 $x = \frac{π}{2} + nπ, n ∈ Z$  
  답은 $\{x | x \neq \frac{π}{2} + nπ, n ∈ Z\}$  
- 치역: 모든 실수

## 4번 문제

### 함수 $y = 2x^3 + 3$이 단사함수임을 증명하여라.

단사 함수: 서로 다른 x값에 대해 서로 다른 y값을 가지는 함수  
즉, $x₁ \neq x₂$이면 $y₁ \neq y₂$  
이의 대우는 $y₁ = y₂$이면 $x₁ = x₂$이다.  
이에 따라 식을 전개해보면  
$2(x₁)^3 + 3 = 2(x₂)^3 + 3$  
$(x₁)^3 = (x₂)^3$  
$(x₁ - x₂)((x₁)^2 + x₁x₂ + (x₂)^2)$ = 0  
$x₁ = x₂$  
즉 위의 식은 단사함수임을 증명할 수 있다.

# 1장 4절
## 3번 문제
### 다음 수열 중 아래로 유계인 수열과 위로 유계인 수열을 찾아라.

#### 1. $\{\frac{(-1)^n}{(n+1)}\}$

$(n + 1) > 1$  
$\frac{1}{(n + 1)} < 1$  
$(-1)^n$은 -1과 1을 번갈아가며 가짐  
즉, 해당 수식은 -1과 1 사이의 값을 가지므로 위로 유계인 동시에 아래로 유계인 수열이다.  

#### 2. $\{cos(\frac{n\pi}{2})\}$

위 식은 -1과 1 사이의 값을 가지므로 위로 유계인 동시에 아래로 유계인 수열이다.  

#### 3. $\{2^n\}$

위 식은 2의 n승으로 n이 증가할수록 값이 무한대로 증가하므로 상계가 존재하지 않는다.  
모든 항이 1보다 크므로 아래로 유계이다.  

#### 4. $\{(-2)^n\}$

위 식은 무한대로 증가하거나 감소하므로 상계, 하계가 없다.  
즉 유계가 아님.  


**위로 유계:    1번, 2번  
아래로 유계:  1번, 2번, 3번  **

## 4번 문제
### 다음 각 수열에 대하여 열린구간 (2-0.1, 2+0.1) 안에 들어가는 항과 들어가지 않는 항을 찾아라.

#### 1. $\{2 - \frac{1}{n}\}$

$2 - 0.1 < 2 - \frac{1}{n} < 2 + 0.1$  
$-0.1 < \frac{1}{n} < 0.1$  
$n > 10$  
따라서 11번째 항부터 구간에 들어감.  
**들어가는 항: 11번째 항부터**  
**들어가지 않는 항: 1 ~ 10**  

#### 2. $\{\frac{2n}{(n+1)}\}$

$2 - 0.1 < \frac{2n}{(n+1)} < 2 + 0.1$  
$1.9n + 1.9 < 2n < 2.1n + 2.1$  
$1.9 < 0.1n$  
$19 < n$  
**들어가는 항: 20, 21, 22, ...**  
**들어가지 않는 항: 1~19번째 항**  

#### 3. $\{2 + (\frac{-1}{2})^n\}$

$2 - 0.1 < 2 + (\frac{-1}{2})^n < 2 + 0.1$  
$-0.1 < (\frac{-1}{2})^n < 0.1$

n이 짝수인 경우  
$-0.1 < (\frac{1}{2})^n < 0.1$  
$2^n > 10$
4, 6, 8, 10, ...번째 항이 포함된다.  

n이 홀수인 경우  
$0.1 > (\frac{1}{2})^n$ 혹은 $(\frac{1}{2})^n > -0.1$  
$10 < 2^n$ 혹은 $2^n < -10$  
n = 4일때 16이므로 4번째 항부터 포함된다.  
즉 5, 7, 9, 11, ...번째 항이 포함된다.  
**들어가는 항: 4, 5, 6, 7, ...번째 항**
**들어가지 않는 항: 나머지**  

# 1장 5절
## 9번 문제
### 다음 우극한과 좌극한을 구하여라.

#### 1. $lim_{x \to 2^{+}} \frac{[x]^2 - 4}{x^2 - 4}$
$lim_{x \to 2^{+}} [x] = 2$  
$lim_{x \to 2^{+}} \frac{2^2 - 4}{x^2 - 4} = 0$  
분자가 0이므로 답은 0

#### 2. $lim_{x \to 2^{-}} \frac{[x]^2 - 4}{x^2 - 4}$
$lim_{x \to 2^{-}} [x] = 1$  
$lim_{x \to 2^{-}} \frac{1^2 - 4}{x^2 - 4} = lim_{x \to 2^{-}} \frac{-3}{x^2 - 4}$ = -\infty$  
따라서 답은 $-\infty$

#### 3. $lim_{x \to 3^{+}} (x - 2 + [2-x] - [x])$

$lim_{x \to 3^{+}} (x - 2)$ + $lim_{x \to 3^{+}} [2 - x]$ + $lim_{x \to 3^{+}} [x]$  
= 1 + (-1) + 3 = 3  
따라서 답은 3  

#### 4. $lim_{x \to 3^{-}} (x - 2 + [2-x] - [x])$

$lim_{x \to 3^{-}} (x - 2)$ + $lim_{x \to 3^{-}} [2 - x]$ + $lim_{x \to 3^{-}} [x]$  
= 1 + (-2) + 2 = 1  
따라서 답은 1  

#### 5. $lim_{x \to 0^{+}} \frac{\sqrt{x}}{\sqrt{4+\sqrt{x}} - 2}$

0을 바로 대입하면 분모가 0이 되어버린다.  
따라서 다음과 같이 식을 다시 구성해준다.  
$lim_{x \to 0^{+}} \frac{\sqrt{x}(\sqrt{4+\sqrt{x}} + 2)}{\sqrt{x}}$  
= $lim_{x \to 0^{+}} \sqrt{4 + \sqrt{x}} + 2$  
이제 다시 0을 넣어서 계산해보면 답은 4.

## 12번 문제
### 다음 극한이 존재하면 그 값을 구하여라.

#### 1. $lim_{x \to 1} \frac{1 + \sqrt{x}}{1 - x}$

$lim_{x \to 1} {\frac{1}{1 - \sqrt{x}}}$로 치환 가능.  
$x = 1$에서 극한값이 존재하지 않음.  

#### 2. $lim_{x \to a} \frac{x^n - a^n}{x - a}$ (단, n은 자연수, a는 상수)

$x^n - a^n = (x - a)(x^{n-1} + x^{n-2}a + x^{n-3}a^2 + ... + a^{n-1})$  
따라서 $lim_{x \to a} \frac{x^n - a^n}{x - a}$ = $lim_{x \to a} (x^{n-1} + x^{n-2}a + x^{n-3}a^2 + ... + a^{n-1})$  
$x$에 $a$를 대입하면 식은 다음과 같다.  
$a^{n-1} + a^{n-2}a + a^{n-3}a^2 + ... + a^{n-1}$  
= $n * a^{n-1}$  
**답은 $n * a^{n-1}$**

#### 3. $lim_{x \to 1} \frac{x - 1}{\sqrt{2 + x} + 1}$
변수에 1을 넣어서 계산해주겠다.  
**답은 0**  

#### 4. $lim_{x \to 1} \frac{(x - 2)(\sqrt{x} - 1)}{x^2 + x - 2}$
치환을 해주겠다.  
$lim_{x \to 1} \frac{(x - 2)(\sqrt{x} - 1)}{(x + 2)(x - 1)}$  
= $lim_{x \to 1} \frac{(x - 2)(x - 1)}{(x + 2)(x - 1)(\sqrt{x} + 1)}$  
= $lim_{x \to 1} \frac{x - 2}{(x + 2)(\sqrt{x} + 1)}$  
**답은 $-\frac{1}{6}$**

#### 5. $lim_{x \to 1} \frac{1 - \sqrt{x}}{1 - x}$

1번 문제와 마찬가지로 치환을 통해 문제를 풀 수 있다.  
$lim_{x \to 1} {\frac{1}{1 + \sqrt{x}}}$ = $\frac{1}{2}$  
**답은 $\frac{1}{2}$**  

# 1장 6절
## 4번 문제
### 다음 함수의 불연속점을 구하고 그 점에서 불연속인 이유를 설명하여라

#### 1. $f(x) = \frac{x}{x}$

$x = 0$에서 정의되지 않으므로 $x = 0$에서 불연속이다.

#### 2. $f(x) = \frac{x^2}{x+1}$

$x = -1$에서 정의되지 않으므로 $x = -1$에서 불연속이다.

#### 3. $f(x) = \sin \frac{1}{x}$

$x = 0$에서 정의되지 않으므로 $x = 0$에서 불연속이다.

#### 4. $f(x) = [x] + [-x]$
$[x]$와 $[-x]$는 $x$가 정수일 때 불연속이다.  
따라서 모든 정수에서 불연속이다.

#### 5. $f(x) = x - [x]$

$[x]$는 $x$가 정수일 때 불연속이다.  
따라서 모든 정수에서 불연속이다.


## 5번 문제
### 다음 함수가 연속함수가 되도록 불연속인 점에서의 함숫값을 정의하여라.

#### 1. $f(x) = \frac{x^2 - 1}{x - 1}$

$x = 1$에서 정의되지 않으므로 $x = 1$에서 불연속이다.  
따라서 인수분해를 이용해 식을 변형해서 함숫값을 정의해보겠다.  
$f(x) = \frac{(x - 1)(x + 1)}{x - 1} = x + 1$  
$x = 1$에서의 함숫값은 2이다.

#### 2. $f(x) = \frac{x^2 - 4}{x^3 - 8}$

$x = 2$에서 정의되지 않으므로 $x = 2$에서 불연속이다.  
마찬가지로 인수분해를 이용해 함숫값을 정의해보겠다.  
$f(x) = \frac{(x - 2)(x + 2)}{(x - 2)(x^2 + 2x + 4)} = \frac{x + 2}{x^2 + 2x + 4}$  
$x = 2$에서 함숫값은 $\frac{1}{3}$이다.

#### 3. $f(x) = \frac{1 - \sqrt{x}}{1 - x}$

$x = 1$에서 정의되지 않으므로 $x = 1$에서 불연속이다.  
역시 마찬가지로 인수분해를 이용해보겠다.  
$f(x) = \frac{1 - x}{(1 - x)(1 + \sqrt{x})} = \frac{1}{1 + \sqrt{x}}$
$x = 1$에성 함숫값은 $\frac{1}{2}$이다.

