## 1
### a

```{r}
a <- seq(5, -11, -0.3)
a
```

### b

```{r}
b <- a[length(a):1]
b
```

## 2
### a

```{r}
a <- c(seq(3, 6, length.out=5), rep(c(2, -5.1, -33), 2), 7/42 + 2)
a
```

### b

```{r}
b <- a[c(-1, -length(a))]
b
```

### c

```{r}
sort(b, decreasing=TRUE)
```

## 3
### a

```{r}
a <- matrix(c(4.3, 3.1, 8.2, 8.2, 3.2, 0.9, 1.6, 6.5), 4, 2, byrow=TRUE)
a
a <- rbind(c(4.3, 3.1), c(8.2, 8.2), c(3.2, 0.9), c(1.6, 6.5))
a
```

### b

```{r}
a[, 2] <- sort(a[, 2])
```

### c

```{r}
for (i in 1:ncol(a)) {
  a[, i] <- sort(a[, i])
}
a
```

## 4
### a

```{r}
dframe <- data.frame(person=c('Stan', 'Francine', 'Steve', 'Roger', 'Hayley', 'Klaus'), sex=factor(c('M', 'F', 'M', 'M', 'F', 'M')), funny=factor(c('High', 'Mid', 'Low', 'High', 'Mid', 'Mid'), ordered=TRUE, levels=c('Low', 'Mid', 'High')))
str(dframe)
```

### b

```{r}
dframe['gpa'] = c(3.5, 3.5, 3.0, 4.1, 2.8, 3.9)
dframe
```

### c

```{r}
dframe[substr(dframe$person, 1, 1) == 'S', ]
```

### d

```{r}
dframe['sex'] <- ifelse(dframe$sex == 'M', 0, 1)
dframe
```

## 5

```{r}
sortMatrix <- function (mat) {
  for (i in 1:ncol(mat)) {
    mat[, i] <- sort(mat[, i])
  }
  return (mat)
}
yo <- matrix(c(2345, 123, 46 , 234, 2134 , 1 ,124 ,134), 2)
yo <- sortMatrix(yo)
yo
```

## 6
### a

```{r}
a <- quakes
str(a)
```

### b

```{r}
mean(a$mag)
median(a$mag)
a.tab <- table(a$mag)
a.tab[a.tab == max(a.tab)]
summary(a$mag)
```

### c

```{r}
var(a$mag)
sd(a$mag)
IQR(a$mag)
sd(a$mag) / mean(a$mag)
```

### d

```{r}
table(a$mag)
barplot(table(a$mag))
```

### e

```{r}
hist(a$mag)
```

### f

```{r}
hist(a$mag, breaks=seq(4, 6.4, 0.1), main='0.1 space', col='green', xlab='mag', ylab='count')
hist(a$mag, breaks=seq(4, 6.4, 0.3), main='0.3 space', col='blue', xlab='mag', ylab='count')
```

### g

```{r}
par(mfrow=c(2,2))
boxplot(a$lat, main='lat', col='pink')
boxplot(a$long, main='long', col='red')
boxplot(a$depth, main='depth', col='blue')
boxplot(a$mag, main='mag', col='green')
```

### h

```{r}
par(mfrow=c(1,1))
pairs(a[, c('lat', 'long', 'depth', 'mag')])
```
