project:
  type: website
  preview:
    host: '0.0.0.0'
    port: 5000


website:
  title: "2024-2 정리노트"
  navbar:
    left:
      - href: human/index.qmd
        text: "인간공학"
      - href: stat/index.qmd
        text: "확률과통계"
      - href: art/index.qmd
        text: "공연예술의이해"
      - href: data/index.qmd
        text: "데이터베이스설계및활용"
      - href: math/index.qmd
        text: "기초공학수학"
      - href: discrete/index.qmd
        text: "이산수학"
        

tools:
  python:
    - { type: "script", file: "scripts/build_menu.py" }

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



