project:
  type: website
  preview:
    host: '0.0.0.0'
    port: 5000

website:
  title: "2024-2 정리노트"
  description: "my 2024-2 note site"
  site-url: "https://cryscham123.github.io"
  site-path: "/2024-2/"
  sidebar:
    - contents: posts/**
  navbar:
    tools:
      - icon: github
        href: https://github.com/cryscham123/2024-2
  page-navigation: true
  page-footer: "Copyright 2024, hyunghoon kim"
  reader-mode: true
  # navbar:
  #   right:
  #     - href: art/index.qmd
  #       text: "공연예술의이해"
  #     - href: data/index.qmd
  #       text: "데이터베이스설계및활용"
  #     - href: math/index.qmd
  #       text: "기초공학수학"
  #     - href: discrete/index.qmd
  #       text: "이산수학"
        

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    font:
      text: "Noto Sans KR"
      heading: "Noto Sans KR"
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700&display=swap" rel="stylesheet">
