---
title: 'Discrete Mathematics #1'
author: "20192208 김형훈"
format: 
  pdf:
    documentclass: report
    papersize: a4
    number-sections: true
    number-depth: 3
    top-level-division: chapter
    fontsize: 17pt
    geometry:
      - top=20mm
include-in-header: 
  text: |
    \usepackage{fontspec}
    \setmainfont{Noto Sans KR}
    \usepackage{titlesec}
    \titleformat{\chapter}{\normalfont\huge\bfseries}{}{0pt}{\huge}
    \titleformat{\section}[block]{\normalfont\Large\bfseries}{}{0pt}{}
    \titleformat{\subsection}[block]{\normalfont\large\bfseries}{}{0pt}{}
    \titleformat{\subsubsection}[block]{\normalfont\normalsize\bfseries}{}{0pt}{}
    \titlespacing*{\chapter}{-3pt}{0pt}{10pt}
    \titlespacing*{\section}{0pt}{20pt}{10pt}
    \newcommand{\sectionbreak}{\clearpage}
    \usepackage{setspace}
    \setstretch{1.5}
    \usepackage{tabularx}
    \newcolumntype{Y}{>{\centering\arraybackslash}X}
---

# 1.1
## Problem 12
**\large Let p and q be the propositions “The election is decided” and “The votes have been counted,” respectively. Express each of these compound propositions as an English sen- tence.**


#### A. ¬p
The election is not decided.

#### B. p∨q
The election is decided or the votes have been counted.

#### C. ¬p∧q
The election is not decided and the votes have been counted.

#### D. q→p
if the votes have been counted, then the election is decided.

#### E. ¬q→¬p 
If the votes have not been counted, then the election is not decided.

#### F. ¬p→¬q
If the election is not decided, then the votes have not been counted.

#### G. p↔q
The election is decided if and only if the votes have been counted.

#### H. ¬q∨(¬p∧ q)
The votes have not been counted or the election is not decided and the votes have been counted.  
another solution: (¬q∨¬p)∧(¬q∨q) ≡ (¬q∨¬p)∧T ≡ (¬q∨¬p)  
The votes have not been counted or the election is not decided.

## Problem 16
**\large Let p, q, and r be the propositions  
p: You get an A on the final exam.  
q: You do every exercise in this book.  
r: You get an A in this class.  
Write these propositions using p, q, and r and logical con-nectives (including negations).**


#### A. You get an A in this class, but you do not do every exercise in this book.
r∧¬q

#### B. You get an A on the final, you do every exercise in this book, and you get an A in this class.
p∧q∧r

#### C. To get an A in this class, it is necessary for you to get an A on the final.
r only if p  
r→p

#### D. You get an A on the final, but you don’t do every ex-ercise in this book; nevertheless, you get an A in this class.
p∧¬q∧r

#### E. Getting an A on the final and doing every exercise in this book is sufficient for getting an A in this class.
(p∧q)→r

#### F. You will getan A in this class if and only if you either do every exercise in this book or you get an A on the final.
r↔(q∨p)

## Problem 26
**\large Write each of these statements in the form “if p, then q” in English.  
[Hint: Refer to the list of common ways to ex-press conditional statements provided in this section.]**


#### A. I will remember to send you the address only if you send me an e-mail message.
If i remember to send you the address, then you send me an e-mail message.

#### B. To be a citizen of this country, it is sufficient that you were born in the United States.
If you were born in the United States, then you are a citizen of this country.

#### C. If you keep your textbook, it will be a useful reference in your future courses.
If you keep your textbook, then it will be a useful reference in your future courses.

#### D. The Red Wings will win the Stanley Cup if their goalie plays well.
If their goalie plays well, then the Red Wings will win the Stanley Cup.

#### E. That you get the job implies that you had the best cre-dentials.
If you get the job, then you had the best credentials.

#### F. The beach erodes whenever there is a storm.
If there is a storm, then the beach erodes.

#### G. It is necessary to have a valid password to log on to the server.
If you log on to the server, then you have a valid password.

#### H. You will reach the summit unless you begin your climb too late.
If you begin your climb too late, then you will not reach the summit.

#### I. You will get a free ice cream cone, provided that you are among the first 100 customers tomorrow.
If you are among the first 100 customers tomorrow, then you will get a free ice cream cone.

## Problem 28
**\large Write each of these propositions in the form “p if and only if q” in English.**


#### A. For you to get an A in this course, it is necessary and sufficient that you learn how to solve discrete mathe-matics problems.
you get an A in this course if and only if you learn how to solve discrete mathematics problems.

#### B. If you read the newspaper every day, you will be in-formed, and conversely.
you read the newspaper every day if and only if you will be informed.

#### C. It rains if it is a weekend day, and it is a weekend day if it rains.
It rains if and only if it is a weekend day.

#### D. You can see the wizard only if the wizard is not in, and the wizard is not in only if you can see him.
you can see the wizard if and only if the wizard is not in.

#### E. My airplane flight is late exactly when I have to catch a connecting flight.
My airplane flight is late if and only if I have to catch a connecting flight.

# 1.3
## Problem 22
**\large Show that p → q and ¬q → ¬p are logically equivalent.**


\begin{tabularx}{\textwidth}{|Y|Y|Y|Y|Y|Y|}
\hline
p & q & p->q & ¬q & ¬p & ¬q->¬p \\
\hline
T & T & T & F & F & T \\
\hline
T & F & F & T & F & F \\
\hline
F & T & T & F & T & T \\ 
\hline
F & F & T & T & T & T \\
\hline
\end{tabularx}

## Problem 30
**\large Show that ¬p → (q → r) and q → (p∨r) are logically equivalent.**


\begin{tabularx}{\textwidth}{|Y|Y|Y|Y|Y|Y|Y|Y|}
\hline
p & q & r & ¬p & q->r & p∨r & ¬p->(q->r) & q->(p∨r) \\
\hline
T & T & T & F & T & T & T & T \\
\hline
T & T & F & F & F & T & T & T \\
\hline
T & F & T & F & T & T & T & T \\
\hline
T & F & F & F & T & T & T & T \\
\hline
F & T & T & T & T & T & T & T \\
\hline
F & T & F & T & F & F & F & F \\
\hline
F & F & T & T & T & T & T & T \\
\hline
F & F & F & T & T & F & T & T \\
\hline
\end{tabularx}

## Problem 63
**\large How many of the disjunctions p∨¬q∨s, ¬p ∨ ¬r∨s, ¬p∨¬r∨¬s, ¬p∨q∨¬s, q∨r∨¬s, q∨¬r∨¬s, ¬p∨¬q∨¬s, p∨r∨s, and p∨r ∨¬s can be made si-multaneously true by an assignment of truth values to p,
q,r,ands?**

p∨¬q∨s ≡ T  
¬p∨¬r∨s ≡ T  
¬p∨¬r∨¬s ≡ F  
¬p∨q∨¬s ≡ T  
q∨r∨¬s ≡ T  
q∨¬r∨¬s ≡ T  
¬p∨¬q∨¬s ≡ F  
p∨r∨s ≡ T  
p∨r∨¬s ≡ T  
**The answer is 7**

## Problem 66
**\large Determine whether each of these compound propositions is satisfiable.**


#### A. (p∨q∨¬r)∧(p∨¬q∨¬s)∧(p∨¬r∨¬s)∧(¬p∨¬q∨¬s)∧(p∨q∨¬s)
(p∨¬q∨¬s)∧(¬p∨¬q∨¬s)∧(p∨q∨¬s)
≡ (p∨¬s)∨(¬q∧q)∧(¬p∨¬q∨¬s) ≡ (p∨¬s)∧(¬p∨¬q∨¬s)  
(p∨q∨¬r)∧(p∨¬r∨¬s)∧(p∨¬s)∧(¬p∨¬q∨¬s)  
≡ ((p∨¬s)∨¬r)∧(p∨¬s)∧(p∨q∨¬r)∧(¬p∨¬q∨¬s)  
≡ (p∨¬s)∧(p∨q∨¬r)∧(¬p∨¬q∨¬s)


\begin{tabularx}{\textwidth}{|Y|Y|Y|Y|Y|Y|Y|}
\hline
p & q & r & s & p∨¬s & p∨q∨¬r & ¬p∨¬q∨¬s \\
\hline
T & T & T & T & T & T & F \\
\hline
T & T & T & F & T & T & T \\
\hline
T & T & F & T & T & T & F \\
\hline
T & T & F & F & T & T & T \\
\hline
T & F & T & T & T & T & T \\
\hline
T & F & T & F & T & T & T \\
\hline
T & F & F & T & T & T & T \\
\hline
T & F & F & F & T & T & T \\
\hline
F & T & T & T & T & T & F \\
\hline
F & T & T & F & T & T & T \\
\hline
F & T & F & T & F & T & T \\
\hline
F & T & F & F & T & T & T \\
\hline
F & F & T & T & F & F & T \\
\hline
F & F & T & F & T & F & T \\
\hline
F & F & F & T & F & T & T \\
\hline
F & F & F & F & T & T & T \\
\hline
\end{tabularx}


Except when (p, q, r, s) is (T T F T), (F T T T) (F T F T), (F F T T), (F F T F), (F F F T) the sentence is correct.  
So, the sentence is satisfiable.

#### B. (¬p∨¬q∨r)∧(¬p∨q∨¬s)∧(p∨¬q∨¬s)∧(¬p ∨ ¬r ∨ ¬s)∧(p ∨ q ∨ ¬r)∧(p ∨ ¬r ∨ ¬s)
Due to the inefficiency of the prior method, subsequent problems will be solved by merely identifying one specific case that satisfies the equation in question.  
When (p, q, r, s) is (T T T F), the sentence is correct.

#### C. (p∨q∨r)∧(p∨¬q∨¬s)∧(q∨¬r∨s)∧(¬p∨r∨s)∧(¬p∨q∨¬s)∧(p∨¬q∨¬r)∧(¬p∨¬q ∨ s)∧(¬p ∨ ¬r ∨ ¬s)
When (p, q, r, s) is (T T F T), the sentence is correct.

# 1.4
## Problem 8
**\large Translate these statements into English, where R(x) is “x is a rabbit” and H(x) is “x hops” and the domain consists of all animals.**


#### A. ∀x(R(x) → H(x))
For all animals, if it is a rabbit, then it hops.

#### B. ∀x(R(x) ∧ H(x))
All animals are rabbits and hop.

#### C. ∃x(R(x) → H(x)) 
There is an animal such that if it is a rabbit, then it hops.

#### D. ∃x(R(x) ∧ H(x))
There is an animal that is a rabbit and hops.

## Problem 16
**\large Determine the truth value of each of these statements if the domain of each variable consists of all real numbers**


#### A. $∃x(x^2 = 2)$
True when $x$ is $\sqrt{2}$ or $-\sqrt{2}$

#### B. $∃x(x^2 = -1)$
False because the answer is $i$ which is not a real number.

#### C. $∀x(x^2 + 2 ≥ 1)$
$x^2 ≥ -1$ is always true.  
So, the answer is True.

#### D. $∀x(x^2 ≠ x)$
False because $x = 1$ is an exception.

## Problem 44
**\large Express each of these system specifications using predicates, quantifiers, and logical connectives.**


#### A. Every user has access to an electronic mailbox.
U(x): x is a user  
M(x): x has access to an electronic mailbox  
∀x(U(x) → M(x))

#### B. The system mailbox can be accessed by everyone in the group if the file system is locked.
L: The file system is locked  
G(x): x is in the group  
A(x): x can access the system mailbox  
L → ∀x(G(x) → A(x))

#### C. The firewall is in a diagnostic state only if the proxy server is in a diagnostic state.
F: The firewall is in a diagnostic state  
P: The proxy server is in a diagnostic state  
F → P

#### D. At least one router is functioning normally if the throughput is between 100 kbps and 500 kbps and the proxy server is not in diagnostic mode.
R(x): x is a router  
F(x): x is functioning normally  
T(x, y): Throughput is between x kbps and y kbps  
P: The proxy server is in a diagnostic state  
(T(100, 500) ∧ ¬P) → ∃x(R(x) ∧ F(x))

# 1.5
## Problem 8
**\large Let Q(x, y) be the statement “Student x has been a contestant on quiz show y.”  
Express each of these sentences in terms of Q(x, y), quantifiers, and logical connectives, where the domain for x consists of all students at your school and for y consists of all quiz shows on television.**


#### A. There is a student at your school who has been a contestant on a television quiz show.
∃x∃yQ(x, y)

#### B. No student at your school has ever been a contestant on a television quiz show.
∀x∀y¬Q(x, y)

#### C. There is a student at your school who has been a contestant on Jeopardy! and on Wheel of Fortune.
∃x(Q(x, Jeopardy)∧Q(x, Wheel of Fortune))

#### D. Every television quiz show has had a student from your school as a contestant.
∀y∃xQ(x, y)

#### E. At least two students from your school have been contestants on Jeopardy!.
∃x∃y((x≠y)∧Q(x, Jeopardy)∧Q(y, Jeopardy))

## Problem 10
**\large Let F(x, y) be the statement “x can fool y,” where the domain consists of all people in the world.  
Use quantifiers to express each of these statements.**


#### A. Everybody can fool Fred.
∀xF(x, Fred)

#### B. Evelyn can fool everybody.
∀yF(Evelyn, y)

#### C. Everybody can fool somebody.
∀x∃yF(x, y)

#### D. There is no one who can fool everybody.
¬∃x∀yF(x, y)

#### E. Everyone can be fooled by somebody.
∀y∃xF(x, y)

#### F. No one can fool both Fred and Jerry.
∀x¬(F(x, Fred)∧F(x, Jerry))

#### G Nancy can fool exactly two people.
∃!x∃!y((x≠y)∧F(Nancy, x)∧F(Nancy, y))

#### H. There is exactly one person whom everybody can fool.
∃!y∀xF(x, y)

#### I. No one can fool himself or herself.
∀x¬F(x, x)

#### J. There is someone who can fool exactly one person besides himself or herself.
∃x∃!yF(x, y)

## Problem 20
**\large Express each of these statements using predicates, quantifiers, logical connectives, and mathematical operators where the domain consists of all integers.**


#### A. The product of two negative integers is positive.
∀x∀y((x < 0 ∧ y < 0) → (x * y > 0))

#### B. The average of two positive integers is positive.
∀x∀y((x > 0 ∧ y > 0) → ((x + y) / 2 > 0))

#### C. The difference of two negative integers is not necessarily negative.
∃x∃y((x < 0 ∧ y < 0) ∧ (x - y ≥ 0))

#### D. The absolute value of the sum of two integers does not exceed the sum of the absolute values of these integers.
∀x∀y(|x + y| ≤ |x| + |y|)

