---
title: '기공수 과제 #2'
author: "20192208 김형훈"
date: "2024-09-24"
categories: ["기초공학수학", "과제"]
description: |
  문제를 같이 적으니까 표절률이 올라가서 이번 과제에서는 풀이만 적었습니다.
format: 
  pdf:
    documentclass: report
    papersize: a4
    number-sections: true
    number-depth: 3
    top-level-division: chapter
    geometry:
      - top=10mm
include-in-header: 
  text: |
    \usepackage{fontspec}
    \setmainfont{Noto Sans KR}
    \usepackage{titlesec}
    \titleformat{\chapter}{\normalfont\huge\bfseries}{}{0pt}{\huge}
    \titleformat{\section}[block]{\normalfont\Large\bfseries}{}{0pt}{}
    \titleformat{\subsection}[block]{\normalfont\large\bfseries}{}{0pt}{}
    \titleformat{\subsubsection}[block]{\normalfont\normalsize\bfseries}{}{0pt}{}
    \titlespacing*{\chapter}{-3pt}{0pt}{10pt}
    \titlespacing*{\section}{0pt}{20pt}{10pt}
    \newcommand{\sectionbreak}{\clearpage}
    \usepackage{setspace}
    \setstretch{2}
    \usepackage{tabularx}
    \newcolumntype{Y}{>{\centering\arraybackslash}X}
---

# 2장 1절
## 4번 문제
### 1
점 0과 1을 지나는 기울기가 3인 직선  
답은 $y = 3x + 1$

### 2
점 4와 2를 지나는 기울기가 $\frac{1}{4}$인 직선  
답은 $y = \frac{1}{4}x + 1$

### 3
점 -1, 1을 지나는 기울기가 2인 직선  
답은 $y = 2x + 3$

### 4
점 $a$, $a^2-2$를 지나는 기울기가 $2a$인 직선  
답은 $y = 2ax - a^2 - 2$

## 5번 문제

### 1
$\frac{f(t) - f(0)}{t - 0}$ = $\frac{2t - 0}{t}$ = 2  
**답은 2**  

### 2
$\frac{f(t) - f(0)}{t - 0}$ = $\frac{\sqrt{t}}{t}$  
**답은 $\frac{\sqrt{t}}{t}$**  

### 3
$\frac{f(t) - f(0)}{t - 0}$ = $\frac{t^2 - 2 + 2}{t}$ = $\frac{t^2}{t}$ = $t$  
**답은 $t$**  

### 4
$\frac{f(t) - f(0)}{t - 0}$ = $\frac{t^2 + t}{t}$ = $t + 1$  
**답은 $t + 1$**  

# 2장 2절
## 3번 문제
### 2
$y' = \frac{0-2x}{(x^2-1)^2}$  
$x$가 2일 때 $\frac{0-2*2}{(2^2-1)^2} = \frac{-4}{9}$  
**답은 $-\frac{4}{9}$**

# 2장 4절
## 4번 문제
### 1
$y' = 14x^6 + 15x^4 - 1$  
$y'' = 84x^5 + 60x^3$  

### 2
$y' = 40x^9 + 18x^5 + 21x^2$  
$y'' = 360x^8 + 90x^4 + 42x$  

### 3
$y' = \sum_{k=1}^{n} (3k+1)kx^{k-1}$  
$y'' = \sum_{k=2}^{n} (3k+1)k(k-1)x^{k-2}$  

### 4
$y' = a$  
$y'' = 0$  

## 7번 문제
$y' = 3x^2$, $y' = 2x + 1$  
$3x^2 = 2x + 1$  
$3x^2 - 2x - 1 = 0$  
$(3x + 1)(x - 1) = 0$  
**답은 $-\frac{1}{3}$, 1**

# 2장 5절
## 7번 문제
n = 1일 때  
$\frac{dy}{dx} = \frac{d}{dx}(xf(x)) = xf′(x) + f(x)$  
n = n + 1일 때  
$\frac{d^{n+1}y}{dx^{n+1}} = \frac{d}{dx}(\frac{d^{n}y}{dx^{n}})$  
$= \frac{d}{dx}(xf^{(n)}(x) + nf^{(n-1)}(x))$  
$= f^{(n)}(x) + xf^{(n+1)}(x) + nf^{(n)}(x)$  
$= xf^{(n+1)}(x) + (n+1)f^{(n)}(x)$  
따라서 $\frac{d^ny}{dx^n}=xf^{(n)}(x) + nf^{(n-1)}(x)$는 성립한다.

# 2장 6절
## 2번 문제
### 1
$y' = \frac{0-4x}{(x^2-1)^2}$  
$x$가 2일 때 $\frac{-8}{9}$  
**답은 $-\frac{8}{9}$**

### 2
$y' = \frac{-2x(2x + 3) -2(4 - x^2)}{(2x+3)^2}$  
$x$가 9일 때 $-\frac{224}{441} = -\frac{32}{63}$  
**답은 $-\frac{32}{63}$**

### 3
$y' = \frac{-2(6x-1)(x^3+1) + 2(3x^2-x+1)(3x^2)}{(x^3+1)^2}$  
$x$가 0일 때 $\frac{2}{1}$  
**답은 2**

### 4
$y' = \frac{2x(3x+1) - 3(x^2+3)}{(3x+1)^2}$  
$x$가 4일 때 $\frac{47}{169}$  
**답은 $\frac{47}{169}$**

# 2장 7절
## 1번 문제
### 1
$2x - 8yy' = 0$  
$\frac{dy}{dx} = y' = \frac{x}{4y}$

### 2
$\frac{1}{2}x^{-\frac{1}{2}} + \frac{1}{2}y^{-\frac{1}{2}}y' = 0$  
$\frac{dy}{dx} = y' = -\frac{x^{-\frac{1}{2}}}{y^{-\frac{1}{2}}} = -\sqrt{\frac{y}{x}}$

### 3
$2yy' + y' = 4x^3$  
$y' = \frac{4x^3}{2y + 1}$
$\frac{dy}{dx} = y' = \frac{4x^3}{2y + 1}$

### 4
$2(2x+y)(2+2y') = 2(x-2y)(1-2y')$  
$4(2x + y) + 2y'(2x + y) = 2(x - 2y) - 4y'(x - 2y)$  
$6x + 8y = -4y'(x-2y) - 2y'(2x + y)$  
$-3x - 4y = 2xy' - 4yy' + 2xy' + yy'$  
$-3x - 4y = 4xy' -3yy' = y'(4x - 3y)$  
$y' = -\frac{3x + 4y}{4x - 3y}$  
$\frac{dy}{dx} = y' = -\frac{3x + 4y}{4x - 3y}$

### 5
$x+\frac{1}{x} = y+\frac{1}{y}$  
$\frac{x^2-1}{x^2} = \frac{y^2-1}{y^2}y'$  
$y' = \frac{y^2(x^2-1)}{x^2(y^2-1)}$  
$\frac{dy}{dx} = y' = \frac{y^2(x^2-1)}{x^2(y^2-1)}$

### 6
$(x^2+y^2)^{\frac{1}{2}} = 2x-1$  
$\frac{1}{2}(x^2+y^2)^{-\frac{1}{2}}(2x+2yy') = 2$  
$(x^2+y^2)^{-\frac{1}{2}}(x+yy') = 2$  
$x+yy' = 2\sqrt{x^2+y^2}$  
$y' = \frac{2\sqrt{x^2+y^2} - x}{y}$  
$\frac{dy}{dx} = y' = \frac{2\sqrt{x^2+y^2} - x}{y}$

## 5번 문제
### 1
$x^5 + (2x)^5 = 33$  
$33x^5 = 33$  
$x = 1$에서 교점을 가진다.  
두 함수의 $x=1$에서의 미분계수를 구하면  
$x=1$일 때 $y' = 2$  
$5x^4 + 5y^4y' = 0$  
$5y^4y' = -5x^4$  
$y' = -\frac{x^4}{y^4}$  
$x=1, y=2$일 때 $y' = -\frac{1}{16}$  
**답은 2, $-\frac{1}{16}$**

### 2
$y = \frac{1}{x+1}$  
$(\frac{1}{x+1})^3 = (x+1)^2$  
$1 = (x+1)^5$  
$x = 0$에서 교점을 가진다.  
두 함수의 $x=0$에서의 미분계수를 구하면  
$y' = -\frac{1}{(x+1)^2}$  
$x=0$일 때 $y' = -1$  
$3y^2y' = 2(x+1)$  
$y' = \frac{2(x+1)}{3y^2}$  
$x=0, y=1$일 때 $y' = \frac{2}{3}$  
**답은 -1, $\frac{2}{3}$**


# 2장 8절
## 1번 문제
### 1
$x = \sqrt{y^3 + 1}$  
$x^2 = y^3 + 1$  
$y^3 = x^2 - 1$  
$y = (x^2 - 1)^{\frac{1}{3}}$  
$y' = \frac{1}{3}(x^2 - 1)^{-\frac{2}{3}}(2x)$  
**답은 $\frac{1}{2}$**

### 2
$(f^{-1})'(12) = \frac{1}{f'(f^{-1}(12))}$  
$f^{-1}(12) = x + \sqrt{x} = 12$  
$x + \sqrt{x} - 12 = 0$  
$(\sqrt{x} - 3)(\sqrt{x} + 4) = 0$  
$f^{-1}(12) = 9$  
$f'(9) = 1 + \frac{1}{6} = \frac{7}{6}$  
**답은 $\frac{6}{7}$**

### 3
$(f^{-1})'(1) = \frac{1}{f'(f^{-1}(1))}$  
$f^{-1}(1) = x^3 + 2x - 2 = 1$  
$x^3 + 2x - 3 = 0$  
$(x-1)(x^2+x+3) = 0$  
$f^{-1}(1) = 1$  
$f'(1) = 3 + 2 = 5$  
**답은 $\frac{1}{5}$**

### 4
$y=x^{-\frac{1}{3}}$  
$y' = -\frac{1}{3}x^{-\frac{4}{3}}$  
**답은 $-\frac{1}{48}$**

