## human factors research categories
- descriptive research: describe(독립변수의 mean,std,...)
- evaluation research: 시스템의 목적을 충족하는지 평가
  - usability testing
  - cost-benefit analysis
- experimanetal research: 실험 해보는거

## field study vs lab experiment
### field study
- 직접 가서 확인하는거.
- uncontrolled
- results may be more generalizable to real-world situations
- higher cost
- difficult to replicate
- difficult to control extraneous variables

### lab experiment
- controlled
- precise replication
- lower cost
- more flexibility
- real-world generalizability may be limited

## human variability
- intra individual variability
- inter individual variability

### handle human variability
- use statistical techniques

## research design
### quantitative research
- correlational observation
- surveys and questionnaires: 랜덤하게 샘플링하는게 중요
- experiments
- archival research

## experimanetal method
circumstances -> behaviors

### type of variables
- independent variable
- dependent variable
- control variable: 이 값은 고정시키고 실험을 진행한다. 일반화하기 어렵게 한다.
- random variable (sigma): 통제할 수 없는 변수. 일반화하기 용이하다.
- confounding variable: 수식에는 포함되지 않지만 주의해야하는 변수. control 변수로 못뺀거

### decide variables
operational definition: 변수를 어떻게 측정할 것인가


#### independent variable
- Range: realistic / select a range taht will show the effect / pilot experiment

#### dependent variable
- reliability: consistent. solution: increase the number of observations
- validity: measure what it is supposed to measure

### **experimental design** (single variable)
- between-subjects design: 각각의 실험군에 다른 사람들을 넣는다.
  **generalibility 높다, intra person variability를 제거할 수 있다.**

- within-subjects design: 같은 사람들을 다른 실험군에 넣는다.
  **cost-effective, less variability, inter person variability를 제거할 수 있다.**

### **experimental design** (multiple variables)
- factorial design: 두개 이상의 독립변수를 조합하여 실험군을 만든다.
  can test the interaction effect

