## human factors research categories
실험을 통해 모형을 구축하고 법칙을 찾는다.
- descriptive research: 관찰을 통해 데이터 묘사
  1. 무엇을 측정할지
  2. 어떻게 숫자로 표현할지
- evaluation research: 시스템의 목적을 충족하는지 평가
  - usability testing
  - cost-benefit analysis
- experimanetal research: 직접 실험해서 변수간 관계를 파악

## research design
### qualitative research
- 보통 마케팅에서 진행.

### quantitative research
- correlational observation
- surveys and questionnaires
  - sample: 랜덤하게 샘플링하는게 중요
  - rating
  - bias
- experiments
- archival research

## field study vs lab experiment
### field study
- 주로 descriptive research, 다른 research도 가능
- 직접 가서 확인하는거.
- 정성적
- uncontrolled
- results may be more generalizable to real-world situations
- higher cost
- difficult to replicate
- difficult to control extraneous variables

### lab experiment
- controlled
- precise replication
- lower cost
- more flexibility
- real-world generalizability may be limited

### why use experimental method
1. humans are variable
  - intra individual variability
  - inter individual variability
2. ways to handle variability
  - use statistical techniques
  - control variability as much as possible

## experimanetal method
circumstances -> behaviors
변수간 인과관계를 파악

### type of variables
- independent variable
- dependent variable
- control variable: 이 값은 고정시키고 실험을 진행한다. 일반화하기 어렵게 한다.
- random variable (sigma): 통제할 수 없는 변수. 일반화하기 용이하다.
- confounding variable: 수식에는 포함되지 않지만 주의해야하는 변수. control 변수로 못뺀거

### decide variables
operational definition: 변수를 어떻게 측정할 것인가


#### independent variable
- Range: realistic / select a range taht will show the effect / pilot experiment

#### dependent variable
- reliability: consistent. solution: increase the number of observations
- validity: measure what it is supposed to measure

### **experimental design** (single variable)
- between-subjects design: 각각의 실험군에 다른 사람들을 넣는다.
  **generalibility 높다, intra person variability를 제거할 수 있다.**

- within-subjects design: 같은 사람들을 다른 실험군에 넣는다.
  **cost-effective, less variability, inter person variability를 제거할 수 있다.**

### **experimental design** (multiple variables)
- factorial design: 두개 이상의 독립변수를 조합하여 실험군을 만든다.
  can test the interaction effect


1. (주관식) Human factors research의 세 가지 주요 카테고리를 나열하시오.
discriptive research, evaluation research, experimental research

2. (빈칸 채우기) discriptive research는 관찰을 통해 데이터를 묘사하는 연구 방법이다.

3. (주관식) Usability testing과 cost-benefit analysis는 어떤 종류의 research에 해당하는가?
evaluation

4. (빈칸 채우기) Quantitative research의 방법 중 하나인 ______에서는 랜덤하게 샘플링하는 것이 중요하다.
experimental research

5. (주관식) Field study의 장점과 단점을 각각 두 가지씩 설명하시오.
장점: 일반화하기 용이하다.
단점: 비용이 많이 든다. 재현이 어렵다.

6. (빈칸 채우기) Lab experiment는 ______ 되어 있고, ______ 복제가 가능하며, 비용이 _______.
통제, 정확한, 낮다

7. (주관식) 실험 방법을 사용하는 이유 두 가지를 설명하시오.
사람들은 다양하다.
통계적 기법을 사용할 수 있다.

8. (빈칸 채우기) 실험에서 ______ 변수는 이 값을 고정시키고 실험을 진행하며, 일반화하기 어렵게 만든다.
controla

9. (주관식) Operational definition이란 무엇인지 설명하시오.

10. (빈칸 채우기) Between-subjects design은 ______를 제거할 수 있고, within-subjects design은 ______를 제거할 수 있다.
